### PR TITLE
Update repo to build with pnpm v7

### PR DESCRIPTION
**Pull request by scottmerchant**
To make it easier to work with both step packages and portal, we are making all step package repos use pnpm v7.9.5 which is the same as the portal.

### CODE REVIEW

**Comment by scottmerchant** [comment]
I have intentionally not added a changeset as no dependencies have changed.

**Comment by geofflamrock** [comment]
Do we need to think about any changes to renovate, as well as anything in `engines` within `package.json` files to ensure everyone is using the correct version of pnpm?

**Comment by scottmerchant** [comment]
I've updated the renovate config and run the Renovate workflow on this branch which succeeded 👍

**Review by geofflamrock — APPROVED** [review]
LGTM

**Pull request merged**
