### PR TITLE
fix: updated scripts for pnpm 7 compatibility

### PR DESCRIPTION
**Pull request by jbristowe**
* replaced filters with recursive option (`-r`)

### CODE REVIEW

**Comment by geofflamrock** [comment]
👋 hey @jbristowe thanks for the PR, were you trying to use pnpm 7 within this repo as part of some other changes you were looking to make? The reason I ask is that at the moment this repo (as well as a number of other ones in the step framework ecosystem) have a requirement not to use pnpm 7 as it has been causing us issues with updating dependencies via renovate. We're looking at how we can better restrict this so it's more obvious to anyone developing in these repos, so just trying to get more information on the scenario behind this PR. Thanks.

**Comment by jbristowe** [comment]
> were you trying to use pnpm 7 within this repo as part of some other changes you were looking to make?

Yes. It seemed to me that a recursive flag was equivalent to using filters. But, I didn't realise that this causes issues with Renovate.

**Comment by shaun-od** [comment]
@jbristowe I have removed myself as a reviewer for now. When the issues with upgrading to pnpm v7 have been resolved we can take a look at this PR again 😄

**Comment by andrewabest** [comment]
This is no longer required, the repo gets along happily with `pnpm v7`

**Pull request closed without merging**
